{% set version = "0.3.6" %}

package:
  name: srtm.py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SRTM.py/SRTM.py-{{ version }}.tar.gz
  sha256: d721741dde00000235b20f0313c2cec62c9238814b3b726310fb24e3b1d9f499

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - gpxpy

test:
  imports:
    - srtm
  commands:
    - pip check
    - gpxelevations -h
  requires:
    - pip

about:
  home: https://github.com/tkrajina/srtm.py
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python parser for the Shuttle Radar Topography Mission elevation data

extra:
  recipe-maintainers:
    - ocefpaf
