{% set version = "0.3.5" %}

package:
  name: srtm.py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SRTM.py/SRTM.py-{{ version }}.tar.gz
  sha256: cb9f8fbb980e2af74ee9c624136dca53af9ad8a36a9e957240e9d9e0f719605d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - gpxpy

test:
  imports:
    - srtm
  commands:
    - pip check
    - gpxelevations -h
  requires:
    - pip

about:
  home: https://github.com/tkrajina/srtm.py
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python parser for the Shuttle Radar Topography Mission elevation data

extra:
  recipe-maintainers:
    - ocefpaf
