{% set version = "0.3.1" %}

package:
  name: srtm.py
  version: {{ version }}

source:
  url: https://github.com/tkrajina/srtm.py/archive/v.{{ version }}.tar.gz
  sha256: 00d58962e991c7d633f65843078b0e1f8e7f534ac1ddfd8c049effcd331ef6ad

build:
  number: 1000
  skip: True  # [py3k]
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - gpxpy

test:
  imports:
    - srtm
  commands:
    - gpxelevations -h

about:
  home: https://github.com/tkrajina/srtm.py
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Python parser for the Shuttle Radar Topography Mission elevation data'

extra:
  recipe-maintainers:
    - ocefpaf
