{% set version = "0.3.4" %}

package:
  name: srtm.py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SRTM.py/SRTM.py-{{ version }}.tar.gz
  sha256: 42cce7a63650963c619c15b749e9d754ad8fa56e277b1529865105275f4e3c9b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - gpxpy

test:
  imports:
    - srtm
  commands:
    - gpxelevations -h

about:
  home: https://github.com/tkrajina/srtm.py
  license: Apache-2.0
  # missing from the sdist
  # license_file: LICENSE.txt
  summary: 'Python parser for the Shuttle Radar Topography Mission elevation data'

extra:
  recipe-maintainers:
    - ocefpaf
