# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HgTAmL5aMlQGpSCQmtdf3fPOn3FTX3BLnPZfB2vxY5dLgJoMkF6BNUiM+0Wj9nZJ+dtfW7sqF9loZaBhiMjmZLkN9AJsVj4vUq48U+f5YAC4CUij21ND1020gsKnsxMp49kX4ifgybvwMH4x2X5m5vMXpJXgZAXhd6PrlaW914NRIW6zTMAP1B3H/X8BUogWm9CORhKOWgMDOSJe5tDCe5aaT0+47ZmWXrlYoKOzB1Fk8oquq2UlwocVpcCVooX1x5P58U6T/NkChca+6zwpI+knm82YwgbKa3yZLZIdA+gyr/L6saNHuYJr1G6zYZ8eq7O/J7SrMXk4EsL+F2DMJey3iafrFy5WRFI4TF5Ij7ohpjA021ZZPsi4y/sbGqIdxHji7OjyV6sOEXtmPcNezC+eA0VWCn5gQ+iq5H3dkN2q6VJS0CpeALp3gtEzBiqA4lwwTbDE9QeuqA4WGJrGB+mr05oGSgR30xOu69QKFZ5N5fjAd8P1KHMfyNNSSdKOz5tTG8dIhUl3PhgvGuYfY2ZJi+tfdeX5DRkFYF9JiXwxIIaFiY8VUqsbFtzcDS2VtWa/6wEIC9XjK5+6M8MY7kbggI27BXdGluWQKEs88x4lC755THuOLK/i8iuHmuGE3Pioyo6hP67ULUM63eBQxxOMx/lD+wHYusyv0+/NFJ4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
