# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HgTAmL5aMlQGpSCQmtdf3fPOn3FTX3BLnPZfB2vxY5dLgJoMkF6BNUiM+0Wj9nZJ+dtfW7sqF9loZaBhiMjmZLkN9AJsVj4vUq48U+f5YAC4CUij21ND1020gsKnsxMp49kX4ifgybvwMH4x2X5m5vMXpJXgZAXhd6PrlaW914NRIW6zTMAP1B3H/X8BUogWm9CORhKOWgMDOSJe5tDCe5aaT0+47ZmWXrlYoKOzB1Fk8oquq2UlwocVpcCVooX1x5P58U6T/NkChca+6zwpI+knm82YwgbKa3yZLZIdA+gyr/L6saNHuYJr1G6zYZ8eq7O/J7SrMXk4EsL+F2DMJey3iafrFy5WRFI4TF5Ij7ohpjA021ZZPsi4y/sbGqIdxHji7OjyV6sOEXtmPcNezC+eA0VWCn5gQ+iq5H3dkN2q6VJS0CpeALp3gtEzBiqA4lwwTbDE9QeuqA4WGJrGB+mr05oGSgR30xOu69QKFZ5N5fjAd8P1KHMfyNNSSdKOz5tTG8dIhUl3PhgvGuYfY2ZJi+tfdeX5DRkFYF9JiXwxIIaFiY8VUqsbFtzcDS2VtWa/6wEIC9XjK5+6M8MY7kbggI27BXdGluWQKEs88x4lC755THuOLK/i8iuHmuGE3Pioyo6hP67ULUM63eBQxxOMx/lD+wHYusyv0+/NFJ4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
