travis:
  secure:
    BINSTAR_TOKEN: xCQS12E9G/wfwaNVymizGcKekLuPWzJ3jU9aXNpm8abBxY58F+jiWLISf2rLE5xbTZHO62O1UpYtZFmYoroIQfcrPu9itQinP1HIaYde380uW2X5YL+a295xuY0diZPd9z/YfQ/4S5vE2h1erJLH989p4g5PyYfv7/QFqn/cXF9rdiz2IETJWRCLc1howpKu4q14Iz+9f1h9TwSOECfH+EegWzf6wnFSzidQJkx86qTDhh0HhTlzZwjlSc8kp5TrNLsqGGaVK+TKH4vdWIfzStLzOSXvGQ2eJjwOhEQct4+k+eyg0ZJBhabLrpQmh7HBxt3J1b5fg2SU9GEO8ftc+a47r6QqYWAC9wBqLLhwxEIA7Wlxrkr9pumvhtQ6Jo8tO1GO1juMs7dS8wCn5p6jpj1v3cUJsxEs2eOLn1YIKb0VAVpk5BX7pwrga7pLk5aMKL4crz4BszNISZjDLSBPGcyiWx3c2tU0vDPbkyjc1STQ/j8Py62b6o9ZNTFUPoHv5AAIKBvFQJcQ/6588pIjl2RQu5W90RhWMOjq7uBXWeXR0fC4R67/WIHuBwV+yMuT12nYwwo/ILki3JdwI8pZ805mq+b5NTYpRxyYgUbkfQbWu82K7fI5i5J3p4eun8gLf1kWtGl491zwlWIzOLpNdjlRYVL+5GDvA0jqC4D2n+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
